/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadRouteImport } from './routes/Squad'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as HonoursRouteImport } from './routes/honours'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as AboutSubSectionRouteImport } from './routes/about/$subSection'
import { Route as AboutFacilitiesPageRouteImport } from './routes/about/FacilitiesPage'
import { Route as AboutFacilitiesRouteImport } from './routes/about/facilities'
import { Route as AboutSponsorsRouteImport } from './routes/about/sponsors'
import { Route as AcademySubSectionRouteImport } from './routes/academy/$subSection'
import { Route as AccountSubSectionRouteImport } from './routes/account/$subSection'
import { Route as FansSubSectionRouteImport } from './routes/fans/$subSection'
import { Route as FoundationSubSectionRouteImport } from './routes/foundation/$subSection'
import { Route as ShopSubSectionRouteImport } from './routes/shop/$subSection'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as VideosVideoIdRouteImport } from './routes/videos/$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/Squad',
  path: '/Squad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const HonoursRoute = HonoursRouteImport.update({
  id: '/honours',
  path: '/honours',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSubSectionRoute = AboutSubSectionRouteImport.update({
  id: '/about/$subSection',
  path: '/about/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFacilitiesPageRoute = AboutFacilitiesPageRouteImport.update({
  id: '/about/FacilitiesPage',
  path: '/about/FacilitiesPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFacilitiesRoute = AboutFacilitiesRouteImport.update({
  id: '/about/facilities',
  path: '/about/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSponsorsRoute = AboutSponsorsRouteImport.update({
  id: '/about/sponsors',
  path: '/about/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySubSectionRoute = AcademySubSectionRouteImport.update({
  id: '/academy/$subSection',
  path: '/academy/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSubSectionRoute = AccountSubSectionRouteImport.update({
  id: '/account/$subSection',
  path: '/account/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const FansSubSectionRoute = FansSubSectionRouteImport.update({
  id: '/fans/$subSection',
  path: '/fans/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationSubSectionRoute = FoundationSubSectionRouteImport.update({
  id: '/foundation/$subSection',
  path: '/foundation/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSubSectionRoute = ShopSubSectionRouteImport.update({
  id: '/shop/$subSection',
  path: '/shop/$subSection',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Squad': typeof SquadRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/honours': typeof HonoursRoute
  '/hospitality': typeof HospitalityRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/tickets': typeof TicketsRoute
  '/about/$subSection': typeof AboutSubSectionRoute
  '/about/FacilitiesPage': typeof AboutFacilitiesPageRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/sponsors': typeof AboutSponsorsRoute
  '/academy/$subSection': typeof AcademySubSectionRoute
  '/account/$subSection': typeof AccountSubSectionRoute
  '/fans/$subSection': typeof FansSubSectionRoute
  '/foundation/$subSection': typeof FoundationSubSectionRoute
  '/shop/$subSection': typeof ShopSubSectionRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Squad': typeof SquadRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/honours': typeof HonoursRoute
  '/hospitality': typeof HospitalityRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/tickets': typeof TicketsRoute
  '/about/$subSection': typeof AboutSubSectionRoute
  '/about/FacilitiesPage': typeof AboutFacilitiesPageRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/sponsors': typeof AboutSponsorsRoute
  '/academy/$subSection': typeof AcademySubSectionRoute
  '/account/$subSection': typeof AccountSubSectionRoute
  '/fans/$subSection': typeof FansSubSectionRoute
  '/foundation/$subSection': typeof FoundationSubSectionRoute
  '/shop/$subSection': typeof ShopSubSectionRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Squad': typeof SquadRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/honours': typeof HonoursRoute
  '/hospitality': typeof HospitalityRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/tickets': typeof TicketsRoute
  '/about/$subSection': typeof AboutSubSectionRoute
  '/about/FacilitiesPage': typeof AboutFacilitiesPageRoute
  '/about/facilities': typeof AboutFacilitiesRoute
  '/about/sponsors': typeof AboutSponsorsRoute
  '/academy/$subSection': typeof AcademySubSectionRoute
  '/account/$subSection': typeof AccountSubSectionRoute
  '/fans/$subSection': typeof FansSubSectionRoute
  '/foundation/$subSection': typeof FoundationSubSectionRoute
  '/shop/$subSection': typeof ShopSubSectionRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Squad'
    | '/contact'
    | '/fixtures'
    | '/honours'
    | '/hospitality'
    | '/membership'
    | '/news'
    | '/tickets'
    | '/about/$subSection'
    | '/about/FacilitiesPage'
    | '/about/facilities'
    | '/about/sponsors'
    | '/academy/$subSection'
    | '/account/$subSection'
    | '/fans/$subSection'
    | '/foundation/$subSection'
    | '/shop/$subSection'
    | '/videos/$videoId'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Squad'
    | '/contact'
    | '/fixtures'
    | '/honours'
    | '/hospitality'
    | '/membership'
    | '/news'
    | '/tickets'
    | '/about/$subSection'
    | '/about/FacilitiesPage'
    | '/about/facilities'
    | '/about/sponsors'
    | '/academy/$subSection'
    | '/account/$subSection'
    | '/fans/$subSection'
    | '/foundation/$subSection'
    | '/shop/$subSection'
    | '/videos/$videoId'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/Squad'
    | '/contact'
    | '/fixtures'
    | '/honours'
    | '/hospitality'
    | '/membership'
    | '/news'
    | '/tickets'
    | '/about/$subSection'
    | '/about/FacilitiesPage'
    | '/about/facilities'
    | '/about/sponsors'
    | '/academy/$subSection'
    | '/account/$subSection'
    | '/fans/$subSection'
    | '/foundation/$subSection'
    | '/shop/$subSection'
    | '/videos/$videoId'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SquadRoute: typeof SquadRoute
  ContactRoute: typeof ContactRoute
  FixturesRoute: typeof FixturesRoute
  HonoursRoute: typeof HonoursRoute
  HospitalityRoute: typeof HospitalityRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  TicketsRoute: typeof TicketsRoute
  AboutSubSectionRoute: typeof AboutSubSectionRoute
  AboutFacilitiesPageRoute: typeof AboutFacilitiesPageRoute
  AboutFacilitiesRoute: typeof AboutFacilitiesRoute
  AboutSponsorsRoute: typeof AboutSponsorsRoute
  AcademySubSectionRoute: typeof AcademySubSectionRoute
  AccountSubSectionRoute: typeof AccountSubSectionRoute
  FansSubSectionRoute: typeof FansSubSectionRoute
  FoundationSubSectionRoute: typeof FoundationSubSectionRoute
  ShopSubSectionRoute: typeof ShopSubSectionRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Squad': {
      id: '/Squad'
      path: '/Squad'
      fullPath: '/Squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honours': {
      id: '/honours'
      path: '/honours'
      fullPath: '/honours'
      preLoaderRoute: typeof HonoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$subSection': {
      id: '/about/$subSection'
      path: '/about/$subSection'
      fullPath: '/about/$subSection'
      preLoaderRoute: typeof AboutSubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/FacilitiesPage': {
      id: '/about/FacilitiesPage'
      path: '/about/FacilitiesPage'
      fullPath: '/about/FacilitiesPage'
      preLoaderRoute: typeof AboutFacilitiesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/facilities': {
      id: '/about/facilities'
      path: '/about/facilities'
      fullPath: '/about/facilities'
      preLoaderRoute: typeof AboutFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sponsors': {
      id: '/about/sponsors'
      path: '/about/sponsors'
      fullPath: '/about/sponsors'
      preLoaderRoute: typeof AboutSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$subSection': {
      id: '/academy/$subSection'
      path: '/academy/$subSection'
      fullPath: '/academy/$subSection'
      preLoaderRoute: typeof AcademySubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$subSection': {
      id: '/account/$subSection'
      path: '/account/$subSection'
      fullPath: '/account/$subSection'
      preLoaderRoute: typeof AccountSubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans/$subSection': {
      id: '/fans/$subSection'
      path: '/fans/$subSection'
      fullPath: '/fans/$subSection'
      preLoaderRoute: typeof FansSubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation/$subSection': {
      id: '/foundation/$subSection'
      path: '/foundation/$subSection'
      fullPath: '/foundation/$subSection'
      preLoaderRoute: typeof FoundationSubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$subSection': {
      id: '/shop/$subSection'
      path: '/shop/$subSection'
      fullPath: '/shop/$subSection'
      preLoaderRoute: typeof ShopSubSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SquadRoute: SquadRoute,
  ContactRoute: ContactRoute,
  FixturesRoute: FixturesRoute,
  HonoursRoute: HonoursRoute,
  HospitalityRoute: HospitalityRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  TicketsRoute: TicketsRoute,
  AboutSubSectionRoute: AboutSubSectionRoute,
  AboutFacilitiesPageRoute: AboutFacilitiesPageRoute,
  AboutFacilitiesRoute: AboutFacilitiesRoute,
  AboutSponsorsRoute: AboutSponsorsRoute,
  AcademySubSectionRoute: AcademySubSectionRoute,
  AccountSubSectionRoute: AccountSubSectionRoute,
  FansSubSectionRoute: FansSubSectionRoute,
  FoundationSubSectionRoute: FoundationSubSectionRoute,
  ShopSubSectionRoute: ShopSubSectionRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
